### ISSUE TITLE
Incompatible library

### ISSUE THREAD

**Issue by borbier** [Polidea/FlutterBleLib#452]
I've import the package and tried running but it got error in sdkVersion

```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
E:\Snippets\pre-project-experiment\tryout_ble\android\app\src\debug\AndroidManifest.xml Error:
	uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:flutter_blue] E:\Snippets\pre-project-experiment\tryout_ble\build\flutter_blue\intermediates\library_manifest\debug\AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="com.pauldemarco.flutter_blue" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:flutter_blue] E:\Snippets\pre-project-experiment\tryout_ble\build\flutter_blue\intermediates\library_manifest\debug\AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 19,
  		or use tools:overrideLibrary="com.pauldemarco.flutter_blue" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 14s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

Here is the packages in pubspec.yml
```
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_blue: ^0.7.0
```

Any workaround for this issue?
