### ISSUE TITLE
Request support the null-safety 

### ISSUE THREAD

**Issue by JonYun** [Polidea/FlutterBleLib#598]
Dear FlutterBleLib team, I am very eager for this library to support null-safety

**Comment by ifredom** [comment]
+1  . wait for null-safety

**Comment by leech001** [comment]
Add on pubspec.yaml
```
  flutter_ble_lib:
    git:
      url: git://github.com/Polidea/FlutterBleLib
      ref: develop
```
