### ISSUE TITLE
Dart 3 incompatible

### ISSUE THREAD

**Issue by patolax** [Polidea/FlutterBleLib#628]
We have been using this great lib for the last 2 years. Worked flawlessly on Android. We are about to go into production but we can't upgrade to new Flutter versions. Can someone please let us know if there is anything happening in the next few months to resolve these issues? or let us know a good alternative you recommend. 

@srgtuszy @PabloPL @dustin-graham  @lukerayman @KKonradMC @dariuszseweryn @mikolak @pouljohn1 @pawelByszewski 

We appreciate any help. Thank you.

**Comment by Peterkrol12** [comment]
Hi!

[This fork](https://github.com/davejlin/flutter_ble_lib_ios_15) was made a while back to support iOS 15, in recent days I've made some changes to the package to also properly support Android 13.

You could try and use this package, but you would have to include it as a git reference package as the changes for Android 13 are not yet deployed to a version:

```
  flutter_ble_lib_ios_15:
    git:
      url: https://github.com/davejlin/flutter_ble_lib_ios_15.git
      ref: 16a56f1433bfdb948bbe1cb0c40e66de27b8ba9f
```
